env_files = [
    "./.env"
]

[tasks.docker-compose-up]
description = "Make docker swarm up and running"
# Never run as independent task
private = true
workspace = false
command = "docker-compose"
args = [
    "up", "-d"
]

[tasks.start]
description = "Run serve in development mode"
# only run if PORT  is set, otherwise skipped
condition = { env_set = [ "PORT" ] }
# run in specified directory
cwd = "./backend"
workspace = false
dependencies = ["docker-compose-up"]
command = "systemfd"
args = [
    "--no-pid",
    "-s", "http::${PORT}",
    "--", "cargo", "watch", "-x", "run"
]
