env_files = [
    "./.env"
]


[tasks.start]
# only run if PORT  is set, otherwise skipped
condition = { env_set = [ "PORT" ] }
description = "Run serve in development mode"
workspace = false
command = "systemfd"
args = [
    "--no-pid",
    "-s", "http::${PORT}",
    "--", "cargo", "watch", "-x", "run"
]
