env_files = [
    "./.env"
]

[tasks.install-cargo-watch]
install_crate = { crate_name = "cargo-watch", binary = "cargo", test_arg = ["watch", "--version"] }
command = "cargo"
args = ["watch", "--version"]

[tasks.docker-compose-up]
description = "Make docker swarm up and running"
# Never run as independent task
private = true
cwd = "./docker"
workspace = false
command = "docker-compose"
args = [
    "up", "-d"
]

# TODO: Need rust commnad line tool to setup index
[tasks.check-index]
description = "Make sure the existence of index"
condtion = { env_set = ["ES_HOST", "ES_PORT"] }
dependencies = ["docker-compose-up"]
workspace = false
command = "curl"
args = [
    "-I", "localhost:9200/monq?pretty"
]

[tasks.create-index]
description = "Create index"
dependencies = ["docker-compose-up"]
cwd = "./docker/elasticsearch"
workspace = false
condtion = { env_set = ["ES_HOST", "ES_PORT"]}
command = "curl"
args = [
    "-X", "PUT", "${ES_HOST}:${ES_PORT}/monq",
    "-H", "Content-Type: application/json",
    "-d", "@index.json"
]

[tasks.delete-index]
description = "Delete index"
dependencies = ["docker-compose-up"]
workspace = false
command = "curl"
args = [
    "-X", "DELETE", "${ES_HOST}:${ES_PORT}/monq?pretty",
]

[tasks.test-sudachi]
description = "Test sudachi analyzer"
dependencies = ["docker-compose-up"]
workspace = false
command = "curl"
args = [
    "-X", "POST", "localhost:9200/monq/_analyze?pretty",
    "-H", "Content-Type: application/json",
    "-d", "@${@}"
]

[tasks.start]
description = "Run serve in development mode"
# only run if PORT  is set, otherwise skipped
condition = { env_set = [ "PORT" ] }
# run in specified directory
cwd = "./backend"
workspace = false
dependencies = ["docker-compose-up", "install-cargo-watch"]
install_crate = "systemfd"
command = "systemfd"
args = [
    "--no-pid",
    "-s", "http::${PORT}",
    "--", "cargo", "watch", "-x", "run"
]
